version: '3.1'

services:
  user-service:
    build: ./user-service
    ports:
    - 50053:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_NAME: "demo"
      DB_HOST: "mysql"
      DB_PORT: "3306"
      DB_USER: "root"
      DB_PASSWORD: "abc123456"
    depends_on:
    - mysql
  user-cli:
    build: ./user-cli
    environment:
      MICRO_REGISTRY: "mdns"